version: "3.3"
services:
  lib:
    build:
      context: ./
      dockerfile: Dockerfile.build
      args:
        - GITHUB_RUN_NUMBER=${GITHUB_RUN_NUMBER}
        - BUILD_HASH=${BUILD_HASH}
        - NPM_TOKEN=${NPM_TOKEN}
  test:
    build:
      context: ./
      dockerfile: Dockerfile.test
